### ISSUE TITLE
Runner.app: No such file or directory

### ISSUE THREAD

**Issue by kubajakowski** [otusweb/xCode-test-bundle-builder-for-bitrise#1]
Step fails with following message at the end:

`find: build/Build/Products/*-iphoneos/MYAPP-Runner.app: No such file or directory`

**Comment by otusweb** [comment]
Can you give more details? Ideally a project to repro the issue?

This error means that at the end of the build phase it cannot find the app that was built.

**Comment by kubajakowski** [comment]
running it locally I have found that missing file has different name than the script is looking for. Instead of `MYAPP-Runner.app` Xcode's build generates `MYAPPUITests-Runner.app`

**Comment by kubajakowski** [comment]
Solved. It started running when right scheme name for UITest target was provided.
