### ISSUE TITLE
xcode-test-bundle-builder@0.0.7 (exit code: 1)   

### ISSUE THREAD

**Issue by zebpaysagar** [otusweb/xCode-test-bundle-builder-for-bitrise#3]
xcode-test-bundle-builder@0.0.7 (exit code: 1)   
▸ Running script '[CP] Embed Pods Frameworks'
▸ Running script '[CP] Copy Pods Resources'
▸ Touching ZebPayTests.xctest
▸ Test build Succeeded
find: build/Build/Products/*-iphoneos/App*-Runner.app: No such file or directory

**Comment by otusweb** [comment]
Did you check the content of  "build/Build/Products/*-iphoneos/"? What do you have in that folder?
You'll want to run the step locally to see the content of the directory or archive that path in bitrise to see it

**Comment by zebpaysagar** [comment]
yes it has been fixed. 
The issues was with the name of the target.
closing it and thanks.
